-- Per-user NATS JWT config (Synadia-parity create/edit fields).

ALTER TABLE nats_account_users
    ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS pub_allow TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS pub_deny TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS sub_allow TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS sub_deny TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS max_subs BIGINT NOT NULL DEFAULT -1,
    ADD COLUMN IF NOT EXISTS max_payload BIGINT NOT NULL DEFAULT -1,
    ADD COLUMN IF NOT EXISTS jwt_lifetime_ns BIGINT NOT NULL DEFAULT 0;
