apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-consol.fullname" . }}-config
  labels:
    {{- include "nats-consol.labels" . | nindent 4 }}
data:
  NATS_URL: {{ .Values.config.natsUrl | quote }}
  NATS_MONITORING_URL: {{ .Values.config.monitoringUrl | quote }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  DEFAULT_CLUSTER_NAME: {{ .Values.config.defaultClusterName | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  {{- with .Values.config.natsTlsCaFile }}
  NATS_TLS_CA_FILE: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.natsTlsCertFile }}
  NATS_TLS_CERT_FILE: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.natsTlsKeyFile }}
  NATS_TLS_KEY_FILE: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.natsTlsServerName }}
  NATS_TLS_SERVER_NAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.natsCredsFile }}
  NATS_CREDS_FILE: {{ . | quote }}
  {{- end }}
