// Code generated by envgen. DO NOT EDIT.

package config

import (
	"github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := ReloadConfig(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	return loadConfig(cfg, env.Snapshot())
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func (c Config) Masked() Config {
	out := c
	out.AdminPassword = env.SensitiveMask
	out.EncryptionKey = env.SensitiveMask
	out.SessionSecret = env.SensitiveMask
	out.OIDCClientSecret = env.SensitiveMask
	return out
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "HTTP_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.HTTPAddr = ":8080"
		} else {
			cfg.HTTPAddr = raw
		}
	}
	{
		key := "DATABASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.DatabaseURL = "postgres://natsconsol:natsconsol@localhost:5432/natsconsol?sslmode=disable"
		} else {
			cfg.DatabaseURL = raw
		}
	}
	{
		key := "ENCRYPTION_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.EncryptionKey = raw
		}
	}
	{
		key := "NATS_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.NATSURL = "nats://localhost:4222"
		} else {
			cfg.NATSURL = raw
		}
	}
	{
		key := "NATS_CREDS_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATSCredsFile = raw
		}
	}
	{
		key := "NATS_TOKEN"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATSToken = raw
		}
	}
	{
		key := "NATS_MONITORING_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.MonitoringURL = "http://localhost:8222"
		} else {
			cfg.MonitoringURL = raw
		}
	}
	{
		key := "REQUEST_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, "10s", err)
			} else {
				cfg.RequestTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, raw, err)
			} else {
				cfg.RequestTimeout = v
			}
		}
	}
	{
		key := "STATIC_DIR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.StaticDir = raw
		}
	}
	{
		key := "ADMIN_USERNAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.AdminUsername = "admin"
		} else {
			cfg.AdminUsername = raw
		}
	}
	{
		key := "ADMIN_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.AdminPassword = "admin"
		} else {
			cfg.AdminPassword = raw
		}
	}
	{
		key := "AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "AuthEnabled", key, "true", err)
			} else {
				cfg.AuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "AuthEnabled", key, raw, err)
			} else {
				cfg.AuthEnabled = v
			}
		}
	}
	{
		key := "DEFAULT_CLUSTER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.DefaultClusterName = "default"
		} else {
			cfg.DefaultClusterName = raw
		}
	}
	{
		key := "ENV"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.Env = "development"
		} else {
			cfg.Env = raw
		}
	}
	{
		key := "CORS_ALLOWED_ORIGINS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.CORSAllowedOrigins = raw
		}
	}
	{
		key := "SESSION_SECRET"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.SessionSecret = raw
		}
	}
	{
		key := "SESSION_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("8h")
			if err != nil {
				env.AppendParse(&errs, "SessionTTL", key, "8h", err)
			} else {
				cfg.SessionTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "SessionTTL", key, raw, err)
			} else {
				cfg.SessionTTL = v
			}
		}
	}
	{
		key := "OIDC_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "OIDCEnabled", key, "false", err)
			} else {
				cfg.OIDCEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "OIDCEnabled", key, raw, err)
			} else {
				cfg.OIDCEnabled = v
			}
		}
	}
	{
		key := "OIDC_ISSUER"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.OIDCIssuer = raw
		}
	}
	{
		key := "OIDC_CLIENT_ID"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.OIDCClientID = raw
		}
	}
	{
		key := "OIDC_CLIENT_SECRET"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.OIDCClientSecret = raw
		}
	}
	{
		key := "OIDC_REDIRECT_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.OIDCRedirectURL = raw
		}
	}
	{
		key := "BASIC_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "BasicAuthEnabled", key, "true", err)
			} else {
				cfg.BasicAuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "BasicAuthEnabled", key, raw, err)
			} else {
				cfg.BasicAuthEnabled = v
			}
		}
	}
	{
		key := "METRICS_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, "false", err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, raw, err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		}
	}
	{
		key := "LOG_JSON"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "LogJSON", key, "false", err)
			} else {
				cfg.LogJSON = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "LogJSON", key, raw, err)
			} else {
				cfg.LogJSON = v
			}
		}
	}
	{
		key := "OPENAPI_PATH"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.OpenAPIPath = "api/openapi.yaml"
		} else {
			cfg.OpenAPIPath = raw
		}
	}
	return env.NewError(errs)
}
