// Code generated by envgen. DO NOT EDIT.

package config

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, env.Snapshot()); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	var next Config
	if err := loadConfig(&next, env.Snapshot()); err != nil {
		return err
	}
	*cfg = next
	return nil
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func (c Config) Masked() Config {
	out := c
	out.NATS.AccountSeed = env.SensitiveMask
	out.AI.APIKey = env.SensitiveMask
	out.SMTP.Password = env.SensitiveMask
	out.Auth.SessionPrivateKey = env.SensitiveMask
	out.EncryptionKey = env.SensitiveMask
	out.AdminPassword = env.SensitiveMask
	return out
}

var configAuditSchema = []env.SchemaField{
	{Key: "PROJECT_NAME", FieldPath: "ProjectName", Required: true},
	{Key: "HTTP_ADDR", FieldPath: "HTTP.Addr", Default: ":8080", HasDefault: true},
	{Key: "HTTP_WRITE_TIMEOUT", FieldPath: "HTTP.WriteTimeout", Default: "30s", HasDefault: true},
	{Key: "HTTP_READ_TIMEOUT", FieldPath: "HTTP.ReadTimeout", Default: "10s", HasDefault: true},
	{Key: "HTTP_IDLE_TIMEOUT", FieldPath: "HTTP.IdleTimeout", Default: "60s", HasDefault: true},
	{Key: "MAX_REQUEST_BODY_SIZE", FieldPath: "HTTP.MaxRequestBodySize", Default: "1048576", HasDefault: true},
	{Key: "HTTP_RESPONSE_COMPRESSION", FieldPath: "HTTP.ResponseCompression", Default: "true", HasDefault: true},
	{Key: "DATABASE_URL", FieldPath: "DB.URL", Required: true},
	{Key: "DB_MAX_CONN_LIFETIME", FieldPath: "DB.MaxConnLifetime", Default: "1h", HasDefault: true},
	{Key: "DB_HEALTH_CHECK_PERIOD", FieldPath: "DB.HealthCheckPeriod", Default: "1m", HasDefault: true},
	{Key: "DB_MAX_CONN_IDLE_TIME", FieldPath: "DB.MaxConnIdleTime", Default: "30m", HasDefault: true},
	{Key: "DB_MAX_CONNS", FieldPath: "DB.MaxConns", Default: "25", HasDefault: true},
	{Key: "DB_MIN_CONNS", FieldPath: "DB.MinConns", Default: "2", HasDefault: true},
	{Key: "NATS_URL", FieldPath: "NATS.URL", Prefix: "NATS_"},
	{Key: "NATS_CREDS_FILE", FieldPath: "NATS.CredsFile", Prefix: "NATS_"},
	{Key: "NATS_TOKEN", FieldPath: "NATS.Token", Prefix: "NATS_"},
	{Key: "NATS_ACCOUNT_SEED", FieldPath: "NATS.AccountSeed", Prefix: "NATS_", Sensitive: true},
	{Key: "NATS_MONITORING_URL", FieldPath: "NATS.MonitoringURL", Prefix: "NATS_"},
	{Key: "NATS_TLS_CA_FILE", FieldPath: "NATS.TlsCAFile", Prefix: "NATS_"},
	{Key: "NATS_TLS_CERT_FILE", FieldPath: "NATS.TlsCertFile", Prefix: "NATS_"},
	{Key: "NATS_TLS_KEY_FILE", FieldPath: "NATS.TlsKeyFile", Prefix: "NATS_"},
	{Key: "NATS_TLS_SERVER_NAME", FieldPath: "NATS.TlsServerName", Prefix: "NATS_"},
	{Key: "NATS_CLIENT_CACHE_TTL", FieldPath: "NATS.ClientCacheTTL", Default: "5m", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_INITIAL_RETRY_ATTEMPTS", FieldPath: "NATS.InitialRetryAttempts", Default: "0", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_MAX_RECONNECT", FieldPath: "NATS.MaxReconnect", Default: "-1", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_RECONNECT_WAIT", FieldPath: "NATS.ReconnectWait", Default: "2s", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_ALLOW_RECONNECT", FieldPath: "NATS.AllowReconnect", Default: "true", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_TLS_INSECURE_SKIP_VERIFY", FieldPath: "NATS.TlsInsecureSkipVerify", Default: "false", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_DONT_RANDOMIZE", FieldPath: "NATS.DontRandomize", Default: "false", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_ALLOW_METRICS", FieldPath: "NATS.AllowMetrics", Default: "true", Prefix: "NATS_", HasDefault: true},
	{Key: "NATS_ALLOW_TRACING", FieldPath: "NATS.AllowTracing", Default: "true", Prefix: "NATS_", HasDefault: true},
	{Key: "AI_GEMINI_API_BASE", FieldPath: "AI.GeminiAPIBase", Default: "https://generativelanguage.googleapis.com/v1beta", Prefix: "AI_", HasDefault: true},
	{Key: "AI_MODEL", FieldPath: "AI.Model", Default: "gemini-2.5-flash", Prefix: "AI_", HasDefault: true},
	{Key: "AI_API_KEY", FieldPath: "AI.APIKey", Prefix: "AI_", Sensitive: true},
	{Key: "AI_CONTEXT_CACHE_TTL", FieldPath: "AI.ContextCacheTTL", Default: "45s", Prefix: "AI_", HasDefault: true},
	{Key: "AI_REQUEST_TIMEOUT", FieldPath: "AI.RequestTimeout", Default: "60s", Prefix: "AI_", HasDefault: true},
	{Key: "AI_MAX_TOKENS", FieldPath: "AI.MaxTokens", Default: "4096", Prefix: "AI_", HasDefault: true},
	{Key: "AI_ENABLED", FieldPath: "AI.Enabled", Default: "false", Prefix: "AI_", HasDefault: true},
	{Key: "SMTP_FROM", FieldPath: "SMTP.From", Prefix: "SMTP_"},
	{Key: "SMTP_PASSWORD", FieldPath: "SMTP.Password", Prefix: "SMTP_", Sensitive: true},
	{Key: "SMTP_USERNAME", FieldPath: "SMTP.Username", Prefix: "SMTP_"},
	{Key: "SMTP_HOST", FieldPath: "SMTP.Host", Prefix: "SMTP_", Required: true},
	{Key: "SMTP_PORT", FieldPath: "SMTP.Port", Prefix: "SMTP_", Required: true},
	{Key: "SMTP_TIMEOUT", FieldPath: "SMTP.Timeout", Default: "15s", Prefix: "SMTP_", HasDefault: true},
	{Key: "SMTP_ENABLED", FieldPath: "SMTP.Enabled", Default: "false", Prefix: "SMTP_", HasDefault: true},
	{Key: "SMTP_TLS", FieldPath: "SMTP.TLS", Default: "true", Prefix: "SMTP_", HasDefault: true},
	{Key: "SESSION_PRIVATE_KEY", FieldPath: "Auth.SessionPrivateKey", Required: true, Sensitive: true},
	{Key: "SESSION_PUBLIC_KEY", FieldPath: "Auth.SessionPublicKey", Required: true},
	{Key: "SESSION_TTL", FieldPath: "Auth.SessionTTL", Default: "15m", HasDefault: true},
	{Key: "REFRESH_TOKEN_TTL", FieldPath: "Auth.RefreshTokenTTL", Default: "168h", HasDefault: true},
	{Key: "AUTH_RATE_LIMIT_WINDOW", FieldPath: "Auth.RateLimitWindow", Default: "1m", HasDefault: true},
	{Key: "AUTH_RATE_LIMIT", FieldPath: "Auth.RateLimit", Default: "10", HasDefault: true},
	{Key: "LIVE_WS_IDLE_TIMEOUT", FieldPath: "LiveWS.IdleTimeout", Default: "5m", Prefix: "LIVE_WS_", HasDefault: true},
	{Key: "LIVE_WS_RATE_LIMIT", FieldPath: "LiveWS.RateLimit", Default: "100ms", Prefix: "LIVE_WS_", HasDefault: true},
	{Key: "LIVE_WS_MAX_MESSAGES", FieldPath: "LiveWS.MaxMessages", Default: "1000", Prefix: "LIVE_WS_", HasDefault: true},
	{Key: "LIVE_WS_PAYLOAD_TRUNCATE_BYTES", FieldPath: "LiveWS.PayloadTruncateBytes", Default: "4096", Prefix: "LIVE_WS_", HasDefault: true},
	{Key: "METRICS_SNAPSHOT_INTERVAL", FieldPath: "MetricsSnapshot.Interval", Default: "60s", Prefix: "METRICS_SNAPSHOT_", HasDefault: true},
	{Key: "METRICS_SNAPSHOT_RETENTION", FieldPath: "MetricsSnapshot.Retention", Default: "168h", Prefix: "METRICS_SNAPSHOT_", HasDefault: true},
	{Key: "METRICS_SNAPSHOT_BOTTLENECK_RETENTION", FieldPath: "MetricsSnapshot.BottleneckRetention", Default: "672h", Prefix: "METRICS_SNAPSHOT_", HasDefault: true},
	{Key: "METRICS_SNAPSHOT_CLEANUP_INTERVAL", FieldPath: "MetricsSnapshot.CleanupInterval", Default: "1h", Prefix: "METRICS_SNAPSHOT_", HasDefault: true},
	{Key: "PPROF_CPU_MAX_SECONDS", FieldPath: "Pprof.CPUMaxSeconds", Default: "120", Prefix: "PPROF_", HasDefault: true},
	{Key: "PPROF_AUTH_ENABLED", FieldPath: "Pprof.AuthEnabled", Default: "true", Prefix: "PPROF_", HasDefault: true},
	{Key: "PPROF_ENABLED", FieldPath: "Pprof.Enabled", Default: "false", Prefix: "PPROF_", HasDefault: true},
	{Key: "SLOW_CONSUMER_PENDING_THRESHOLD", FieldPath: "SlowConsumer.PendingThreshold", Default: "1000", Prefix: "SLOW_CONSUMER_", HasDefault: true},
	{Key: "SLOW_CONSUMER_LAG_THRESHOLD", FieldPath: "SlowConsumer.LagThreshold", Default: "1000", Prefix: "SLOW_CONSUMER_", HasDefault: true},
	{Key: "SLOW_CONSUMER_ACK_PENDING_RATIO", FieldPath: "SlowConsumer.AckPendingRatio", Default: "0.9", Prefix: "SLOW_CONSUMER_", HasDefault: true},
	{Key: "PAGINATION_MAX_LIMIT", FieldPath: "Pagination.MaxLimit", Default: "500", Prefix: "PAGINATION_", HasDefault: true},
	{Key: "PAGINATION_DEFAULT_LIMIT", FieldPath: "Pagination.DefaultLimit", Default: "100", Prefix: "PAGINATION_", HasDefault: true},
	{Key: "ENCRYPTION_KEY", FieldPath: "EncryptionKey", Required: true, Sensitive: true},
	{Key: "STATIC_DIR", FieldPath: "StaticDir"},
	{Key: "ADMIN_USERNAME", FieldPath: "AdminUsername", Default: "admin", HasDefault: true},
	{Key: "ADMIN_PASSWORD", FieldPath: "AdminPassword", Required: true, Sensitive: true},
	{Key: "PUBLIC_BASE_URL", FieldPath: "PublicBaseURL", Default: "http://localhost:8080", HasDefault: true},
	{Key: "DEFAULT_CLUSTER_NAME", FieldPath: "DefaultClusterName", Default: "default", HasDefault: true},
	{Key: "CORS_ALLOWED_ORIGINS", FieldPath: "CORSAllowedOrigins"},
	{Key: "TRUSTED_PROXIES", FieldPath: "TrustedProxies"},
	{Key: "BEHAVIOR_FINGERPRINT_KV_BUCKET", FieldPath: "BehaviorFingerprintKVBucket", Default: "nats_consol_fingerprints", HasDefault: true},
	{Key: "REQUEST_TIMEOUT", FieldPath: "RequestTimeout", Default: "10s", HasDefault: true},
	{Key: "LOOKBACK_DURATION", FieldPath: "LookBackDuration"},
	{Key: "HEALTH_CHECK_TIMEOUT", FieldPath: "HealthCheckTimeout", Default: "2s", HasDefault: true},
	{Key: "JETSTREAM_VIEW_CACHE_TTL", FieldPath: "JetStreamViewCacheTTL", Default: "3s", HasDefault: true},
	{Key: "INVITE_TTL", FieldPath: "InviteTTL", Default: "24h", HasDefault: true},
	{Key: "MAX_MONITORING_BODY_BYTES", FieldPath: "MaxMonitoringBodyBytes", Default: "8388608", HasDefault: true},
	{Key: "AUDIT_DEFAULT_LIMIT", FieldPath: "AuditDefaultLimit", Default: "50", HasDefault: true},
	{Key: "METRICS_AUTH_ENABLED", FieldPath: "MetricsAuthEnabled", Default: "false", HasDefault: true},
}

func AuditConfig(snap *env.EnvSnapshot) env.AuditReport {
	return env.Audit(snap, configAuditSchema, env.AuditOptions{})
}

func AuditConfigWithOptions(snap *env.EnvSnapshot, opts env.AuditOptions) env.AuditReport {
	return env.Audit(snap, configAuditSchema, opts)
}

func AuditConfigFromEnviron() env.AuditReport {
	return AuditConfig(env.Snapshot())
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "PROJECT_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "ProjectName", key)
		} else {
			cfg.ProjectName = raw
		}
	}
	{
		key := "HTTP_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := ":8080"
			cfg.HTTP.Addr = v
		} else {
			cfg.HTTP.Addr = raw
		}
	}
	{
		key := "HTTP_WRITE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("30s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.WriteTimeout", key, "30s", err)
			} else {
				cfg.HTTP.WriteTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.WriteTimeout", key, raw, err)
			} else {
				cfg.HTTP.WriteTimeout = v
			}
		}
	}
	{
		key := "HTTP_READ_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.ReadTimeout", key, "10s", err)
			} else {
				cfg.HTTP.ReadTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.ReadTimeout", key, raw, err)
			} else {
				cfg.HTTP.ReadTimeout = v
			}
		}
	}
	{
		key := "HTTP_IDLE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.IdleTimeout", key, "60s", err)
			} else {
				cfg.HTTP.IdleTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.IdleTimeout", key, raw, err)
			} else {
				cfg.HTTP.IdleTimeout = v
			}
		}
	}
	{
		key := "MAX_REQUEST_BODY_SIZE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("1048576")
			if err != nil {
				env.AppendParse(&errs, "HTTP.MaxRequestBodySize", key, "1048576", err)
			} else {
				cfg.HTTP.MaxRequestBodySize = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.MaxRequestBodySize", key, raw, err)
			} else {
				cfg.HTTP.MaxRequestBodySize = v
			}
		}
	}
	{
		key := "HTTP_RESPONSE_COMPRESSION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "HTTP.ResponseCompression", key, "true", err)
			} else {
				cfg.HTTP.ResponseCompression = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.ResponseCompression", key, raw, err)
			} else {
				cfg.HTTP.ResponseCompression = v
			}
		}
	}
	{
		key := "DATABASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "DB.URL", key)
		} else {
			cfg.DB.URL = raw
		}
	}
	{
		key := "DB_MAX_CONN_LIFETIME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("1h")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnLifetime", key, "1h", err)
			} else {
				cfg.DB.MaxConnLifetime = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnLifetime", key, raw, err)
			} else {
				cfg.DB.MaxConnLifetime = v
			}
		}
	}
	{
		key := "DB_HEALTH_CHECK_PERIOD"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("1m")
			if err != nil {
				env.AppendParse(&errs, "DB.HealthCheckPeriod", key, "1m", err)
			} else {
				cfg.DB.HealthCheckPeriod = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.HealthCheckPeriod", key, raw, err)
			} else {
				cfg.DB.HealthCheckPeriod = v
			}
		}
	}
	{
		key := "DB_MAX_CONN_IDLE_TIME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("30m")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnIdleTime", key, "30m", err)
			} else {
				cfg.DB.MaxConnIdleTime = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnIdleTime", key, raw, err)
			} else {
				cfg.DB.MaxConnIdleTime = v
			}
		}
	}
	{
		key := "DB_MAX_CONNS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("25")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConns", key, "25", err)
			} else {
				cfg.DB.MaxConns = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConns", key, raw, err)
			} else {
				cfg.DB.MaxConns = v
			}
		}
	}
	{
		key := "DB_MIN_CONNS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("2")
			if err != nil {
				env.AppendParse(&errs, "DB.MinConns", key, "2", err)
			} else {
				cfg.DB.MinConns = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MinConns", key, raw, err)
			} else {
				cfg.DB.MinConns = v
			}
		}
	}
	{
		key := "NATS_URL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.URL = raw
		}
	}
	{
		key := "NATS_CREDS_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.CredsFile = raw
		}
	}
	{
		key := "NATS_TOKEN"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.Token = raw
		}
	}
	{
		key := "NATS_ACCOUNT_SEED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.AccountSeed = raw
		}
	}
	{
		key := "NATS_MONITORING_URL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.MonitoringURL = raw
		}
	}
	{
		key := "NATS_TLS_CA_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.TlsCAFile = raw
		}
	}
	{
		key := "NATS_TLS_CERT_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.TlsCertFile = raw
		}
	}
	{
		key := "NATS_TLS_KEY_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.TlsKeyFile = raw
		}
	}
	{
		key := "NATS_TLS_SERVER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.NATS.TlsServerName = raw
		}
	}
	{
		key := "NATS_CLIENT_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("5m")
			if err != nil {
				env.AppendParse(&errs, "NATS.ClientCacheTTL", key, "5m", err)
			} else {
				cfg.NATS.ClientCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.ClientCacheTTL", key, raw, err)
			} else {
				cfg.NATS.ClientCacheTTL = v
			}
		}
	}
	{
		key := "NATS_INITIAL_RETRY_ATTEMPTS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("0")
			if err != nil {
				env.AppendParse(&errs, "NATS.InitialRetryAttempts", key, "0", err)
			} else {
				cfg.NATS.InitialRetryAttempts = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.InitialRetryAttempts", key, raw, err)
			} else {
				cfg.NATS.InitialRetryAttempts = v
			}
		}
	}
	{
		key := "NATS_MAX_RECONNECT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("-1")
			if err != nil {
				env.AppendParse(&errs, "NATS.MaxReconnect", key, "-1", err)
			} else {
				cfg.NATS.MaxReconnect = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.MaxReconnect", key, raw, err)
			} else {
				cfg.NATS.MaxReconnect = v
			}
		}
	}
	{
		key := "NATS_RECONNECT_WAIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("2s")
			if err != nil {
				env.AppendParse(&errs, "NATS.ReconnectWait", key, "2s", err)
			} else {
				cfg.NATS.ReconnectWait = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.ReconnectWait", key, raw, err)
			} else {
				cfg.NATS.ReconnectWait = v
			}
		}
	}
	{
		key := "NATS_ALLOW_RECONNECT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowReconnect", key, "true", err)
			} else {
				cfg.NATS.AllowReconnect = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowReconnect", key, raw, err)
			} else {
				cfg.NATS.AllowReconnect = v
			}
		}
	}
	{
		key := "NATS_TLS_INSECURE_SKIP_VERIFY"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "NATS.TlsInsecureSkipVerify", key, "false", err)
			} else {
				cfg.NATS.TlsInsecureSkipVerify = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.TlsInsecureSkipVerify", key, raw, err)
			} else {
				cfg.NATS.TlsInsecureSkipVerify = v
			}
		}
	}
	{
		key := "NATS_DONT_RANDOMIZE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			// Legacy typo key (prefer DONT above).
			raw, ok = snap.Lookup("NATS_DDNT_RANDOMIZE")
		}
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "NATS.DontRandomize", key, "false", err)
			} else {
				cfg.NATS.DontRandomize = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.DontRandomize", key, raw, err)
			} else {
				cfg.NATS.DontRandomize = v
			}
		}
	}
	{
		key := "NATS_ALLOW_METRICS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowMetrics", key, "true", err)
			} else {
				cfg.NATS.AllowMetrics = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowMetrics", key, raw, err)
			} else {
				cfg.NATS.AllowMetrics = v
			}
		}
	}
	{
		key := "NATS_ALLOW_TRACING"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowTracing", key, "true", err)
			} else {
				cfg.NATS.AllowTracing = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.AllowTracing", key, raw, err)
			} else {
				cfg.NATS.AllowTracing = v
			}
		}
	}
	{
		key := "AI_GEMINI_API_BASE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "https://generativelanguage.googleapis.com/v1beta"
			cfg.AI.GeminiAPIBase = v
		} else {
			cfg.AI.GeminiAPIBase = raw
		}
	}
	{
		key := "AI_MODEL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "gemini-2.5-flash"
			cfg.AI.Model = v
		} else {
			cfg.AI.Model = raw
		}
	}
	{
		key := "AI_API_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.AI.APIKey = raw
		}
	}
	{
		key := "AI_CONTEXT_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("45s")
			if err != nil {
				env.AppendParse(&errs, "AI.ContextCacheTTL", key, "45s", err)
			} else {
				cfg.AI.ContextCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.ContextCacheTTL", key, raw, err)
			} else {
				cfg.AI.ContextCacheTTL = v
			}
		}
	}
	{
		key := "AI_REQUEST_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "AI.RequestTimeout", key, "60s", err)
			} else {
				cfg.AI.RequestTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.RequestTimeout", key, raw, err)
			} else {
				cfg.AI.RequestTimeout = v
			}
		}
	}
	{
		key := "AI_MAX_TOKENS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("4096")
			if err != nil {
				env.AppendParse(&errs, "AI.MaxTokens", key, "4096", err)
			} else {
				cfg.AI.MaxTokens = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.MaxTokens", key, raw, err)
			} else {
				cfg.AI.MaxTokens = v
			}
		}
	}
	{
		key := "AI_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "AI.Enabled", key, "false", err)
			} else {
				cfg.AI.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.Enabled", key, raw, err)
			} else {
				cfg.AI.Enabled = v
			}
		}
	}
	{
		key := "SMTP_FROM"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.SMTP.From = raw
		}
	}
	{
		key := "SMTP_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.SMTP.Password = raw
		}
	}
	{
		key := "SMTP_USERNAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.SMTP.Username = raw
		}
	}
	{
		key := "SMTP_HOST"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "SMTP.Host", key)
		} else {
			cfg.SMTP.Host = raw
		}
	}
	{
		key := "SMTP_PORT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "SMTP.Port", key)
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.Port", key, raw, err)
			} else {
				cfg.SMTP.Port = v
			}
		}
	}
	{
		key := "SMTP_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("15s")
			if err != nil {
				env.AppendParse(&errs, "SMTP.Timeout", key, "15s", err)
			} else {
				cfg.SMTP.Timeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.Timeout", key, raw, err)
			} else {
				cfg.SMTP.Timeout = v
			}
		}
	}
	{
		key := "SMTP_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "SMTP.Enabled", key, "false", err)
			} else {
				cfg.SMTP.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.Enabled", key, raw, err)
			} else {
				cfg.SMTP.Enabled = v
			}
		}
	}
	{
		key := "SMTP_TLS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "SMTP.TLS", key, "true", err)
			} else {
				cfg.SMTP.TLS = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.TLS", key, raw, err)
			} else {
				cfg.SMTP.TLS = v
			}
		}
	}
	{
		key := "SESSION_PRIVATE_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "Auth.SessionPrivateKey", key)
		} else {
			cfg.Auth.SessionPrivateKey = raw
		}
	}
	{
		key := "SESSION_PUBLIC_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "Auth.SessionPublicKey", key)
		} else {
			cfg.Auth.SessionPublicKey = raw
		}
	}
	{
		key := "SESSION_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("15m")
			if err != nil {
				env.AppendParse(&errs, "Auth.SessionTTL", key, "15m", err)
			} else {
				cfg.Auth.SessionTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.SessionTTL", key, raw, err)
			} else {
				cfg.Auth.SessionTTL = v
			}
		}
	}
	{
		key := "REFRESH_TOKEN_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("168h")
			if err != nil {
				env.AppendParse(&errs, "Auth.RefreshTokenTTL", key, "168h", err)
			} else {
				cfg.Auth.RefreshTokenTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RefreshTokenTTL", key, raw, err)
			} else {
				cfg.Auth.RefreshTokenTTL = v
			}
		}
	}
	{
		key := "AUTH_RATE_LIMIT_WINDOW"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("1m")
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimitWindow", key, "1m", err)
			} else {
				cfg.Auth.RateLimitWindow = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimitWindow", key, raw, err)
			} else {
				cfg.Auth.RateLimitWindow = v
			}
		}
	}
	{
		key := "AUTH_RATE_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("10")
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimit", key, "10", err)
			} else {
				cfg.Auth.RateLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimit", key, raw, err)
			} else {
				cfg.Auth.RateLimit = v
			}
		}
	}
	{
		key := "LIVE_WS_IDLE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("5m")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.IdleTimeout", key, "5m", err)
			} else {
				cfg.LiveWS.IdleTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.IdleTimeout", key, raw, err)
			} else {
				cfg.LiveWS.IdleTimeout = v
			}
		}
	}
	{
		key := "LIVE_WS_RATE_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("100ms")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.RateLimit", key, "100ms", err)
			} else {
				cfg.LiveWS.RateLimit = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.RateLimit", key, raw, err)
			} else {
				cfg.LiveWS.RateLimit = v
			}
		}
	}
	{
		key := "LIVE_WS_MAX_MESSAGES"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("1000")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.MaxMessages", key, "1000", err)
			} else {
				cfg.LiveWS.MaxMessages = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.MaxMessages", key, raw, err)
			} else {
				cfg.LiveWS.MaxMessages = v
			}
		}
	}
	{
		key := "LIVE_WS_PAYLOAD_TRUNCATE_BYTES"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("4096")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.PayloadTruncateBytes", key, "4096", err)
			} else {
				cfg.LiveWS.PayloadTruncateBytes = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.PayloadTruncateBytes", key, raw, err)
			} else {
				cfg.LiveWS.PayloadTruncateBytes = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_INTERVAL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Interval", key, "60s", err)
			} else {
				cfg.MetricsSnapshot.Interval = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Interval", key, raw, err)
			} else {
				cfg.MetricsSnapshot.Interval = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_RETENTION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("168h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Retention", key, "168h", err)
			} else {
				cfg.MetricsSnapshot.Retention = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Retention", key, raw, err)
			} else {
				cfg.MetricsSnapshot.Retention = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_BOTTLENECK_RETENTION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("672h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.BottleneckRetention", key, "672h", err)
			} else {
				cfg.MetricsSnapshot.BottleneckRetention = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.BottleneckRetention", key, raw, err)
			} else {
				cfg.MetricsSnapshot.BottleneckRetention = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_CLEANUP_INTERVAL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("1h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.CleanupInterval", key, "1h", err)
			} else {
				cfg.MetricsSnapshot.CleanupInterval = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.CleanupInterval", key, raw, err)
			} else {
				cfg.MetricsSnapshot.CleanupInterval = v
			}
		}
	}
	{
		key := "PPROF_CPU_MAX_SECONDS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("120")
			if err != nil {
				env.AppendParse(&errs, "Pprof.CPUMaxSeconds", key, "120", err)
			} else {
				cfg.Pprof.CPUMaxSeconds = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.CPUMaxSeconds", key, raw, err)
			} else {
				cfg.Pprof.CPUMaxSeconds = v
			}
		}
	}
	{
		key := "PPROF_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "Pprof.AuthEnabled", key, "true", err)
			} else {
				cfg.Pprof.AuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.AuthEnabled", key, raw, err)
			} else {
				cfg.Pprof.AuthEnabled = v
			}
		}
	}
	{
		key := "PPROF_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "Pprof.Enabled", key, "false", err)
			} else {
				cfg.Pprof.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.Enabled", key, raw, err)
			} else {
				cfg.Pprof.Enabled = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_PENDING_THRESHOLD"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseUint64("1000")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.PendingThreshold", key, "1000", err)
			} else {
				cfg.SlowConsumer.PendingThreshold = v
			}
		} else {
			v, err := env.ParseUint64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.PendingThreshold", key, raw, err)
			} else {
				cfg.SlowConsumer.PendingThreshold = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_LAG_THRESHOLD"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseUint64("1000")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.LagThreshold", key, "1000", err)
			} else {
				cfg.SlowConsumer.LagThreshold = v
			}
		} else {
			v, err := env.ParseUint64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.LagThreshold", key, raw, err)
			} else {
				cfg.SlowConsumer.LagThreshold = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_ACK_PENDING_RATIO"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseFloat64("0.9")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.AckPendingRatio", key, "0.9", err)
			} else {
				cfg.SlowConsumer.AckPendingRatio = v
			}
		} else {
			v, err := env.ParseFloat64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.AckPendingRatio", key, raw, err)
			} else {
				cfg.SlowConsumer.AckPendingRatio = v
			}
		}
	}
	{
		key := "PAGINATION_MAX_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("500")
			if err != nil {
				env.AppendParse(&errs, "Pagination.MaxLimit", key, "500", err)
			} else {
				cfg.Pagination.MaxLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pagination.MaxLimit", key, raw, err)
			} else {
				cfg.Pagination.MaxLimit = v
			}
		}
	}
	{
		key := "PAGINATION_DEFAULT_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("100")
			if err != nil {
				env.AppendParse(&errs, "Pagination.DefaultLimit", key, "100", err)
			} else {
				cfg.Pagination.DefaultLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pagination.DefaultLimit", key, raw, err)
			} else {
				cfg.Pagination.DefaultLimit = v
			}
		}
	}
	{
		key := "ENCRYPTION_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "EncryptionKey", key)
		} else {
			cfg.EncryptionKey = raw
		}
	}
	{
		key := "STATIC_DIR"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.StaticDir = raw
		}
	}
	{
		key := "ADMIN_USERNAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "admin"
			cfg.AdminUsername = v
		} else {
			cfg.AdminUsername = raw
		}
	}
	{
		key := "ADMIN_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			env.AppendRequired(&errs, "AdminPassword", key)
		} else {
			cfg.AdminPassword = raw
		}
	}
	{
		key := "PUBLIC_BASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "http://localhost:8080"
			cfg.PublicBaseURL = v
		} else {
			cfg.PublicBaseURL = raw
		}
	}
	{
		key := "DEFAULT_CLUSTER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "default"
			cfg.DefaultClusterName = v
		} else {
			cfg.DefaultClusterName = raw
		}
	}
	{
		key := "CORS_ALLOWED_ORIGINS"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.CORSAllowedOrigins = raw
		}
	}
	{
		key := "TRUSTED_PROXIES"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.TrustedProxies = raw
		}
	}
	{
		key := "BEHAVIOR_FINGERPRINT_KV_BUCKET"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "nats_consol_fingerprints"
			cfg.BehaviorFingerprintKVBucket = v
		} else {
			cfg.BehaviorFingerprintKVBucket = raw
		}
	}
	{
		key := "REQUEST_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, "10s", err)
			} else {
				cfg.RequestTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, raw, err)
			} else {
				cfg.RequestTimeout = v
			}
		}
	}
	{
		key := "LOOKBACK_DURATION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "LookBackDuration", key, raw, err)
			} else {
				cfg.LookBackDuration = v
			}
		}
	}
	{
		key := "HEALTH_CHECK_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("2s")
			if err != nil {
				env.AppendParse(&errs, "HealthCheckTimeout", key, "2s", err)
			} else {
				cfg.HealthCheckTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HealthCheckTimeout", key, raw, err)
			} else {
				cfg.HealthCheckTimeout = v
			}
		}
	}
	{
		key := "JETSTREAM_VIEW_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("3s")
			if err != nil {
				env.AppendParse(&errs, "JetStreamViewCacheTTL", key, "3s", err)
			} else {
				cfg.JetStreamViewCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "JetStreamViewCacheTTL", key, raw, err)
			} else {
				cfg.JetStreamViewCacheTTL = v
			}
		}
	}
	{
		key := "INVITE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseDuration("24h")
			if err != nil {
				env.AppendParse(&errs, "InviteTTL", key, "24h", err)
			} else {
				cfg.InviteTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "InviteTTL", key, raw, err)
			} else {
				cfg.InviteTTL = v
			}
		}
	}
	{
		key := "MAX_MONITORING_BODY_BYTES"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt64("8388608")
			if err != nil {
				env.AppendParse(&errs, "MaxMonitoringBodyBytes", key, "8388608", err)
			} else {
				cfg.MaxMonitoringBodyBytes = v
			}
		} else {
			v, err := env.ParseInt64(raw)
			if err != nil {
				env.AppendParse(&errs, "MaxMonitoringBodyBytes", key, raw, err)
			} else {
				cfg.MaxMonitoringBodyBytes = v
			}
		}
	}
	{
		key := "AUDIT_DEFAULT_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("50")
			if err != nil {
				env.AppendParse(&errs, "AuditDefaultLimit", key, "50", err)
			} else {
				cfg.AuditDefaultLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "AuditDefaultLimit", key, raw, err)
			} else {
				cfg.AuditDefaultLimit = v
			}
		}
	}
	{
		key := "METRICS_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, "false", err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, raw, err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		}
	}
	return env.NewError(errs)
}
