// Code generated by envgen. DO NOT EDIT.

package config

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := ReloadConfig(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	return loadConfig(cfg, env.Snapshot())
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func (c Config) Masked() Config {
	out := c
	out.NATS.AccountSeed = env.SensitiveMask
	out.AI.APIKey = env.SensitiveMask
	out.SMTP.Password = env.SensitiveMask
	out.Auth.SessionPrivateKey = env.SensitiveMask
	out.EncryptionKey = env.SensitiveMask
	out.AdminPassword = env.SensitiveMask
	return out
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "HTTP_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.HTTP.Addr = ":8080"
		} else {
			cfg.HTTP.Addr = raw
		}
	}
	{
		key := "HTTP_WRITE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("30s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.WriteTimeout", key, "30s", err)
			} else {
				cfg.HTTP.WriteTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.WriteTimeout", key, raw, err)
			} else {
				cfg.HTTP.WriteTimeout = v
			}
		}
	}
	{
		key := "HTTP_READ_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.ReadTimeout", key, "10s", err)
			} else {
				cfg.HTTP.ReadTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.ReadTimeout", key, raw, err)
			} else {
				cfg.HTTP.ReadTimeout = v
			}
		}
	}
	{
		key := "HTTP_IDLE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "HTTP.IdleTimeout", key, "60s", err)
			} else {
				cfg.HTTP.IdleTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.IdleTimeout", key, raw, err)
			} else {
				cfg.HTTP.IdleTimeout = v
			}
		}
	}
	{
		key := "MAX_REQUEST_BODY_SIZE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt64("1048576")
			if err != nil {
				env.AppendParse(&errs, "HTTP.MaxRequestBodySize", key, "1048576", err)
			} else {
				cfg.HTTP.MaxRequestBodySize = v
			}
		} else {
			v, err := env.ParseInt64(raw)
			if err != nil {
				env.AppendParse(&errs, "HTTP.MaxRequestBodySize", key, raw, err)
			} else {
				cfg.HTTP.MaxRequestBodySize = v
			}
		}
	}
	{
		key := "DATABASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "DB.URL", key)
		} else {
			cfg.DB.URL = raw
		}
	}
	{
		key := "DB_MAX_CONN_LIFETIME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("1h")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnLifetime", key, "1h", err)
			} else {
				cfg.DB.MaxConnLifetime = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnLifetime", key, raw, err)
			} else {
				cfg.DB.MaxConnLifetime = v
			}
		}
	}
	{
		key := "DB_HEALTH_CHECK_PERIOD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("1m")
			if err != nil {
				env.AppendParse(&errs, "DB.HealthCheckPeriod", key, "1m", err)
			} else {
				cfg.DB.HealthCheckPeriod = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.HealthCheckPeriod", key, raw, err)
			} else {
				cfg.DB.HealthCheckPeriod = v
			}
		}
	}
	{
		key := "DB_MAX_CONN_IDLE_TIME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("30m")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnIdleTime", key, "30m", err)
			} else {
				cfg.DB.MaxConnIdleTime = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConnIdleTime", key, raw, err)
			} else {
				cfg.DB.MaxConnIdleTime = v
			}
		}
	}
	{
		key := "DB_MAX_CONNS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("25")
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConns", key, "25", err)
			} else {
				cfg.DB.MaxConns = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MaxConns", key, raw, err)
			} else {
				cfg.DB.MaxConns = v
			}
		}
	}
	{
		key := "DB_MIN_CONNS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("2")
			if err != nil {
				env.AppendParse(&errs, "DB.MinConns", key, "2", err)
			} else {
				cfg.DB.MinConns = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "DB.MinConns", key, raw, err)
			} else {
				cfg.DB.MinConns = v
			}
		}
	}
	{
		key := "NATS_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.URL = raw
		}
	}
	{
		key := "NATS_CREDS_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.CredsFile = raw
		}
	}
	{
		key := "NATS_TOKEN"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.Token = raw
		}
	}
	{
		key := "NATS_ACCOUNT_SEED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.AccountSeed = raw
		}
	}
	{
		key := "NATS_MONITORING_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.MonitoringURL = raw
		}
	}
	{
		key := "NATS_TLS_CA_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.TlsCAFile = raw
		}
	}
	{
		key := "NATS_TLS_CERT_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.TlsCertFile = raw
		}
	}
	{
		key := "NATS_TLS_KEY_FILE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.TlsKeyFile = raw
		}
	}
	{
		key := "NATS_TLS_SERVER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.NATS.TlsServerName = raw
		}
	}
	{
		key := "NATS_CLIENT_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("5m")
			if err != nil {
				env.AppendParse(&errs, "NATS.ClientCacheTTL", key, "5m", err)
			} else {
				cfg.NATS.ClientCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.ClientCacheTTL", key, raw, err)
			} else {
				cfg.NATS.ClientCacheTTL = v
			}
		}
	}
	{
		key := "NATS_TLS_INSECURE_SKIP_VERIFY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "NATS.TlsInsecureSkipVerify", key, "false", err)
			} else {
				cfg.NATS.TlsInsecureSkipVerify = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "NATS.TlsInsecureSkipVerify", key, raw, err)
			} else {
				cfg.NATS.TlsInsecureSkipVerify = v
			}
		}
	}
	{
		key := "AI_GEMINI_API_BASE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.AI.GeminiAPIBase = "https://generativelanguage.googleapis.com/v1beta"
		} else {
			cfg.AI.GeminiAPIBase = raw
		}
	}
	{
		key := "AI_MODEL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.AI.Model = "gemini-2.5-flash"
		} else {
			cfg.AI.Model = raw
		}
	}
	{
		key := "AI_API_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.AI.APIKey = raw
		}
	}
	{
		key := "AI_CONTEXT_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("45s")
			if err != nil {
				env.AppendParse(&errs, "AI.ContextCacheTTL", key, "45s", err)
			} else {
				cfg.AI.ContextCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.ContextCacheTTL", key, raw, err)
			} else {
				cfg.AI.ContextCacheTTL = v
			}
		}
	}
	{
		key := "AI_REQUEST_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "AI.RequestTimeout", key, "60s", err)
			} else {
				cfg.AI.RequestTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.RequestTimeout", key, raw, err)
			} else {
				cfg.AI.RequestTimeout = v
			}
		}
	}
	{
		key := "AI_MAX_TOKENS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("4096")
			if err != nil {
				env.AppendParse(&errs, "AI.MaxTokens", key, "4096", err)
			} else {
				cfg.AI.MaxTokens = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.MaxTokens", key, raw, err)
			} else {
				cfg.AI.MaxTokens = v
			}
		}
	}
	{
		key := "AI_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "AI.Enabled", key, "false", err)
			} else {
				cfg.AI.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "AI.Enabled", key, raw, err)
			} else {
				cfg.AI.Enabled = v
			}
		}
	}
	{
		key := "SMTP_FROM"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.SMTP.From = raw
		}
	}
	{
		key := "SMTP_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.SMTP.Password = raw
		}
	}
	{
		key := "SMTP_USERNAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.SMTP.Username = raw
		}
	}
	{
		key := "SMTP_HOST"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.SMTP.Host = raw
		}
	}
	{
		key := "SMTP_PORT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("587")
			if err != nil {
				env.AppendParse(&errs, "SMTP.Port", key, "587", err)
			} else {
				cfg.SMTP.Port = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.Port", key, raw, err)
			} else {
				cfg.SMTP.Port = v
			}
		}
	}
	{
		key := "SMTP_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "SMTP.Enabled", key, "false", err)
			} else {
				cfg.SMTP.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.Enabled", key, raw, err)
			} else {
				cfg.SMTP.Enabled = v
			}
		}
	}
	{
		key := "SMTP_TLS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "SMTP.TLS", key, "true", err)
			} else {
				cfg.SMTP.TLS = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "SMTP.TLS", key, raw, err)
			} else {
				cfg.SMTP.TLS = v
			}
		}
	}
	{
		key := "SESSION_PRIVATE_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "Auth.SessionPrivateKey", key)
		} else {
			cfg.Auth.SessionPrivateKey = raw
		}
	}
	{
		key := "SESSION_PUBLIC_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "Auth.SessionPublicKey", key)
		} else {
			cfg.Auth.SessionPublicKey = raw
		}
	}
	{
		key := "SESSION_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("15m")
			if err != nil {
				env.AppendParse(&errs, "Auth.SessionTTL", key, "15m", err)
			} else {
				cfg.Auth.SessionTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.SessionTTL", key, raw, err)
			} else {
				cfg.Auth.SessionTTL = v
			}
		}
	}
	{
		key := "REFRESH_TOKEN_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("168h")
			if err != nil {
				env.AppendParse(&errs, "Auth.RefreshTokenTTL", key, "168h", err)
			} else {
				cfg.Auth.RefreshTokenTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RefreshTokenTTL", key, raw, err)
			} else {
				cfg.Auth.RefreshTokenTTL = v
			}
		}
	}
	{
		key := "AUTH_RATE_LIMIT_WINDOW"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("1m")
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimitWindow", key, "1m", err)
			} else {
				cfg.Auth.RateLimitWindow = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimitWindow", key, raw, err)
			} else {
				cfg.Auth.RateLimitWindow = v
			}
		}
	}
	{
		key := "AUTH_RATE_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("10")
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimit", key, "10", err)
			} else {
				cfg.Auth.RateLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Auth.RateLimit", key, raw, err)
			} else {
				cfg.Auth.RateLimit = v
			}
		}
	}
	{
		key := "LIVE_WS_IDLE_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("5m")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.IdleTimeout", key, "5m", err)
			} else {
				cfg.LiveWS.IdleTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.IdleTimeout", key, raw, err)
			} else {
				cfg.LiveWS.IdleTimeout = v
			}
		}
	}
	{
		key := "LIVE_WS_RATE_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("100ms")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.RateLimit", key, "100ms", err)
			} else {
				cfg.LiveWS.RateLimit = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.RateLimit", key, raw, err)
			} else {
				cfg.LiveWS.RateLimit = v
			}
		}
	}
	{
		key := "LIVE_WS_MAX_MESSAGES"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("1000")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.MaxMessages", key, "1000", err)
			} else {
				cfg.LiveWS.MaxMessages = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.MaxMessages", key, raw, err)
			} else {
				cfg.LiveWS.MaxMessages = v
			}
		}
	}
	{
		key := "LIVE_WS_PAYLOAD_TRUNCATE_BYTES"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("4096")
			if err != nil {
				env.AppendParse(&errs, "LiveWS.PayloadTruncateBytes", key, "4096", err)
			} else {
				cfg.LiveWS.PayloadTruncateBytes = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "LiveWS.PayloadTruncateBytes", key, raw, err)
			} else {
				cfg.LiveWS.PayloadTruncateBytes = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_INTERVAL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("60s")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Interval", key, "60s", err)
			} else {
				cfg.MetricsSnapshot.Interval = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Interval", key, raw, err)
			} else {
				cfg.MetricsSnapshot.Interval = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_RETENTION"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("168h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Retention", key, "168h", err)
			} else {
				cfg.MetricsSnapshot.Retention = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Retention", key, raw, err)
			} else {
				cfg.MetricsSnapshot.Retention = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_BOTTLENECK_RETENTION"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("672h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.BottleneckRetention", key, "672h", err)
			} else {
				cfg.MetricsSnapshot.BottleneckRetention = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.BottleneckRetention", key, raw, err)
			} else {
				cfg.MetricsSnapshot.BottleneckRetention = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_CLEANUP_INTERVAL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("1h")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.CleanupInterval", key, "1h", err)
			} else {
				cfg.MetricsSnapshot.CleanupInterval = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.CleanupInterval", key, raw, err)
			} else {
				cfg.MetricsSnapshot.CleanupInterval = v
			}
		}
	}
	{
		key := "METRICS_SNAPSHOT_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Enabled", key, "true", err)
			} else {
				cfg.MetricsSnapshot.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsSnapshot.Enabled", key, raw, err)
			} else {
				cfg.MetricsSnapshot.Enabled = v
			}
		}
	}
	{
		key := "PPROF_CPU_MAX_SECONDS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("120")
			if err != nil {
				env.AppendParse(&errs, "Pprof.CPUMaxSeconds", key, "120", err)
			} else {
				cfg.Pprof.CPUMaxSeconds = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.CPUMaxSeconds", key, raw, err)
			} else {
				cfg.Pprof.CPUMaxSeconds = v
			}
		}
	}
	{
		key := "PPROF_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "Pprof.AuthEnabled", key, "true", err)
			} else {
				cfg.Pprof.AuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.AuthEnabled", key, raw, err)
			} else {
				cfg.Pprof.AuthEnabled = v
			}
		}
	}
	{
		key := "PPROF_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "Pprof.Enabled", key, "false", err)
			} else {
				cfg.Pprof.Enabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Pprof.Enabled", key, raw, err)
			} else {
				cfg.Pprof.Enabled = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_PENDING_THRESHOLD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseUint64("1000")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.PendingThreshold", key, "1000", err)
			} else {
				cfg.SlowConsumer.PendingThreshold = v
			}
		} else {
			v, err := env.ParseUint64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.PendingThreshold", key, raw, err)
			} else {
				cfg.SlowConsumer.PendingThreshold = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_LAG_THRESHOLD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseUint64("1000")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.LagThreshold", key, "1000", err)
			} else {
				cfg.SlowConsumer.LagThreshold = v
			}
		} else {
			v, err := env.ParseUint64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.LagThreshold", key, raw, err)
			} else {
				cfg.SlowConsumer.LagThreshold = v
			}
		}
	}
	{
		key := "SLOW_CONSUMER_ACK_PENDING_RATIO"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseFloat64("0.9")
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.AckPendingRatio", key, "0.9", err)
			} else {
				cfg.SlowConsumer.AckPendingRatio = v
			}
		} else {
			v, err := env.ParseFloat64(raw)
			if err != nil {
				env.AppendParse(&errs, "SlowConsumer.AckPendingRatio", key, raw, err)
			} else {
				cfg.SlowConsumer.AckPendingRatio = v
			}
		}
	}
	{
		key := "PAGINATION_MAX_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("500")
			if err != nil {
				env.AppendParse(&errs, "Pagination.MaxLimit", key, "500", err)
			} else {
				cfg.Pagination.MaxLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pagination.MaxLimit", key, raw, err)
			} else {
				cfg.Pagination.MaxLimit = v
			}
		}
	}
	{
		key := "PAGINATION_DEFAULT_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("100")
			if err != nil {
				env.AppendParse(&errs, "Pagination.DefaultLimit", key, "100", err)
			} else {
				cfg.Pagination.DefaultLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "Pagination.DefaultLimit", key, raw, err)
			} else {
				cfg.Pagination.DefaultLimit = v
			}
		}
	}
	{
		key := "OPENAPI_PATH"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.OpenAPIPath = "api/openapi.yaml"
		} else {
			cfg.OpenAPIPath = raw
		}
	}
	{
		key := "ENCRYPTION_KEY"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "EncryptionKey", key)
		} else {
			cfg.EncryptionKey = raw
		}
	}
	{
		key := "STATIC_DIR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.StaticDir = raw
		}
	}
	{
		key := "ADMIN_USERNAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.AdminUsername = "admin"
		} else {
			cfg.AdminUsername = raw
		}
	}
	{
		key := "ADMIN_PASSWORD"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			env.AppendRequired(&errs, "AdminPassword", key)
		} else {
			cfg.AdminPassword = raw
		}
	}
	{
		key := "PUBLIC_BASE_URL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.PublicBaseURL = "http://localhost:8080"
		} else {
			cfg.PublicBaseURL = raw
		}
	}
	{
		key := "DEFAULT_CLUSTER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.DefaultClusterName = "default"
		} else {
			cfg.DefaultClusterName = raw
		}
	}
	{
		key := "CORS_ALLOWED_ORIGINS"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.CORSAllowedOrigins = raw
		}
	}
	{
		key := "TRUSTED_PROXIES"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.TrustedProxies = raw
		}
	}
	{
		key := "BEHAVIOR_FINGERPRINT_KV_BUCKET"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.BehaviorFingerprintKVBucket = "nats_consol_fingerprints"
		} else {
			cfg.BehaviorFingerprintKVBucket = raw
		}
	}
	{
		key := "REQUEST_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("10s")
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, "10s", err)
			} else {
				cfg.RequestTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "RequestTimeout", key, raw, err)
			} else {
				cfg.RequestTimeout = v
			}
		}
	}
	{
		key := "HEALTH_CHECK_TIMEOUT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("2s")
			if err != nil {
				env.AppendParse(&errs, "HealthCheckTimeout", key, "2s", err)
			} else {
				cfg.HealthCheckTimeout = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "HealthCheckTimeout", key, raw, err)
			} else {
				cfg.HealthCheckTimeout = v
			}
		}
	}
	{
		key := "JETSTREAM_VIEW_CACHE_TTL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseDuration("3s")
			if err != nil {
				env.AppendParse(&errs, "JetStreamViewCacheTTL", key, "3s", err)
			} else {
				cfg.JetStreamViewCacheTTL = v
			}
		} else {
			v, err := env.ParseDuration(raw)
			if err != nil {
				env.AppendParse(&errs, "JetStreamViewCacheTTL", key, raw, err)
			} else {
				cfg.JetStreamViewCacheTTL = v
			}
		}
	}
	{
		key := "MAX_MONITORING_BODY_BYTES"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt64("8388608")
			if err != nil {
				env.AppendParse(&errs, "MaxMonitoringBodyBytes", key, "8388608", err)
			} else {
				cfg.MaxMonitoringBodyBytes = v
			}
		} else {
			v, err := env.ParseInt64(raw)
			if err != nil {
				env.AppendParse(&errs, "MaxMonitoringBodyBytes", key, raw, err)
			} else {
				cfg.MaxMonitoringBodyBytes = v
			}
		}
	}
	{
		key := "AUDIT_DEFAULT_LIMIT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("50")
			if err != nil {
				env.AppendParse(&errs, "AuditDefaultLimit", key, "50", err)
			} else {
				cfg.AuditDefaultLimit = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "AuditDefaultLimit", key, raw, err)
			} else {
				cfg.AuditDefaultLimit = v
			}
		}
	}
	{
		key := "METRICS_AUTH_ENABLED"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, "false", err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MetricsAuthEnabled", key, raw, err)
			} else {
				cfg.MetricsAuthEnabled = v
			}
		}
	}
	return env.NewError(errs)
}
